- azure/azure-release-pipeline.yml
- manifest_template.yml
> Enable Sandbox

- azure/azure-release-pipeline.yml
- manifest_template.yml
> APM-3095 Uncomment internal qa envs

- _ping
- openapi.json
- sandbox/Dockerfile
> Vtx 60 change port to 9000

- terraform/batch-processing.tf
- terraform/batch-processing/iam.tf
- terraform/batch-processing/lambda.tf
- terraform/batch-processing/s3.tf
- terraform/batch-processing/src/batch_processing.py
- terraform/batch-processing/variables.tf
> AMB-1688: Batch Processing Lambda

- azure/azure-pr-teardown-pipeline.yml
- terraform/variables.tf
> making changes to create pr to test pipeline on

- lambda_code/README.md
- tests/Makefile
- tests/test_search_immunization.py
> Amb 0000 improve tests

- azure/templates/post-deploy.yml
- tests/Makefile
- tests/pytest.ini
- tests/test_endpoints.py
- tests/test_int.py
> AMB-1859-Enable-Imms-FHIR-API-in-INT

- manifest_template.yml
> Amb 1859 enable imms fhir api in int

- specification/immunisation-fhir-api.yaml
> AMB-1885 update spec wording

- specification/immunisation-fhir-api.yaml
> AMB-1885 fix bullet point syntax

- specification/immunisation-fhir-api.yaml
Add extra newline to render bullet points
> AMB-1858 fix bullet points in spec

- specification/immunisation-fhir-api.yaml
> Amb 1858 update spec

- azure/templates/post-deploy.yml
- lambda_code/src/fhir_controller.py
- lambda_code/tests/test_fhir_controller.py
> AMB-000 fix url subdomain in Location header

- azure/azure-release-pipeline.yml
- azure/templates/post-deploy.yml
- manifest_template.yml
> AMB-000 add ref env

- terraform/endpoints.tf
- terraform/policies/secret_manager.json
> AMB-1922 use PDS ref env

- lambda_code/src/pds_service.py
- lambda_code/tests/test_pds_service.py
> Use correct cache key for PDS token; test

- terraform/.terraform.lock.hcl
- terraform/batch_processing.tf
- terraform/batch_processing/cluster.tf
- terraform/batch_processing/variables.tf
> AMB-000 hotfix: use short name for resources

- azure/azure-release-pipeline.yml
Add any other relevant notes or explanations here. **This change is to add manual approval check for Ref environment to restrict auto-deployment. Existing Utils pipeline functionality has been extended tom achieve this. *
> Added manual approval check for Ref

- backend/src/log_structure.py
- backend/src/models/errors.py
- backend/src/not_found_handler.py
- delta_backend/src/delta.py
- terraform/endpoints.tf
- terraform/policies/log_kinesis.json
- terraform/splunk.tf
- terraform/splunk/backup.tf
- terraform/splunk/firehose.tf
- terraform/splunk/iam.tf
- terraform/splunk/outputs.tf
- terraform/splunk/variables.tf
> Amazon-kinesis-to-splunk-logs

- backend/src/fhir_controller.py
- backend/src/fhir_service.py
- backend/src/search_imms_handler.py
- e2e/test_search_immunization.py
- e2e/utils/base_test.py
> Amb 1998   500 response for invalid nhs number

- e2e/test_s3_vaccine_locations.py
- terraform/batch_processing.tf
- terraform/splunk/backup.tf
> Create location in S3 for Batch to identify vaccine type for batch

- .github/workflows/continuous-disintegration.yml
> Testing PR pipeline

- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_controller_authorization.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
- e2e/utils/immunisation_api.py
> Amb 2012 a optimistic locking

- backend/src/models/fhir_immunization_pre_validators.py
- backend/tests/test_immunization_pre_validator.py
> AMB-1906-site-code-value-ODS-format-requirement

- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
> Amb 2054 search immunizations bug fix to use indexed vaccine type

- backend/src/authorization.py
- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/src/models/errors.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_controller_authorization.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
- e2e/test_authorization.py
- e2e/utils/authorization.py
- e2e/utils/factories.py
- proxies/live/apiproxy/policies/AssignMessage.AddAuthorizationHeaders.xml
> AMB-2047-Restrict-Create-to-vaccination-events-of-authorised-vaccine-types

- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/src/models/errors.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_controller_authorization.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
- e2e/test_authorization.py
- e2e/utils/factories.py
> Amb 2044 restrict update to vaccination events of authorised vaccine types

- backend/src/fhir_controller.py
- backend/src/models/fhir_immunization_post_validators.py
- backend/tests/test_immunization_post_validator_model.py
> AMB-2061- Incorrect Validation Rule applied when missing NHSNumber

- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
- e2e/test_authorization.py
- e2e/utils/factories.py
>  AMB-2045-Restrict-Read-to-vaccination-events-of-authorised-vaccine-types 

- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
- e2e/test_authorization.py
- e2e/utils/factories.py
- proxies/live/apiproxy/policies/AssignMessage.AddAuthorizationHeaders.xml
> AMB-2046-Restrict-Delete-to-vaccination-events-of-authorised-vaccine-types

- backend/src/fhir_controller.py
- backend/src/models/errors.py
- backend/tests/test_fhir_controller.py
- e2e/test_authorization.py
- e2e/utils/factories.py
> search vaccine authorization updates

- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/src/models/utils/generic_utils.py
- backend/src/models/utils/validation_utils.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
> AMB:1865 - Update: restrict to authorised system

- backend/src/s_flag_handler.py
- backend/tests/sample_data/completed_covid19_immunization_event_filtered_for_s_flag.json
- backend/tests/sample_data/completed_covid19_immunization_event_filtered_for_s_flag_and_read.json
- backend/tests/test_s_flag_handler.py
- e2e/test_filtering_immunization.py
- e2e/utils/resource.py
> AMB-2057-Sflag amendments for Read

- backend/tests/test_immunization_post_validator_model.py
> AMB 2052 :   fix post validation test collected errors

- backend/src/fhir_service.py
> AMB 2132 : Review use of search bundle.link

- backend/src/models/fhir_immunization_pre_validators.py
- backend/src/models/utils/validation_utils.py
- backend/tests/test_fhir_service.py
- backend/tests/test_immunization_post_validator_model.py
- backend/tests/test_immunization_pre_validator.py
- backend/tests/test_utils.py
- e2e/utils/resource.py
> AMB-2064-Fix-validation-errors

- terraform/batch_processing.tf
- terraform/policies/s3_batch.json
- terraform/policies/s3_batch_policy.json
- terraform/policies/s3_batch_policy_prod.json
> AMB-2117-DPS-role

- backend/src/fhir_repository.py
> AMB-2147 Re-instated Deleted record is not retrievable in READ/SEARCH

- backend/src/fhir_repository.py
- backend/tests/test_fhir_repository.py
> Amb 2159 search to include reinstated records

- delta_backend/src/convert_flat_json.py
- delta_backend/src/delta.py
- delta_backend/tests/__init__.py
- delta_backend/tests/test_delta.py
> AMB-2109 : Convert FHIR Json to Flat Json in Delta Dynamo

- backend/src/fhir_controller.py
- backend/src/update_imms_handler.py
- backend/tests/test_update_imms.py
- delta_backend/src/delta.py
> AMB-2184-Default-Supplier-in-Delta

- delta_backend/src/delta.py
> AMB-2180-DPS-records-not-be-written-to-Delta 

- backend/src/fhir_controller.py
- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- backend/src/models/errors.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_controller_authorization.py
- backend/tests/test_fhir_repository.py
- backend/tests/test_fhir_service.py
- e2e/utils/factories.py
- proxies/live/apiproxy/policies/AssignMessage.AddAuthorizationHeaders.xml
> Capture Supplier System

- delta_backend/src/delta.py
> removed default supplier_system in delta table

- backend/src/fhir_controller.py
> Obtain supplier system for batch app

- delta_backend/src/delta.py
> Continue after DPS record. Amend operation outcome keys for consistency

- backend/src/fhir_controller.py
> fix batch supplier system for all environments

- .github/workflows/continuous-disintegration.yml
> AMB-0007-PR teardown with SP

- backend/src/filter.py
- backend/tests/sample_data/completed_covid19_immunization_event_filtered_for_s_flag.json
- backend/tests/test_s_flag_handler.py
> Amb-2160 : S-Flag filtering doesn't account for additional valid FHIR

- backend/src/models/fhir_immunization_post_validators.py
- backend/src/models/obtain_field_value.py
- backend/tests/test_immunization_post_validator.py
> Remove unneeded post validation

- backend/src/models/fhir_immunization_pre_validators.py
- backend/tests/test_immunization_post_validator.py
- backend/tests/test_immunization_pre_validator.py
> Raise mandatory error when targetDisease absent

- backend/src/fhir_controller.py
- backend/src/fhir_service.py
- backend/src/models/constants.py
- backend/src/models/fhir_immunization_pre_validators.py
- backend/src/models/utils/generic_utils.py
- backend/tests/test_fhir_controller.py
- backend/tests/test_fhir_service.py
- backend/tests/test_immunization_pre_validator.py
- e2e/test_create_immunization.py
> Amb 2170 validation amendments pre validation mandation

- backend/src/models/utils/pre_validator_utils.py
- backend/tests/test_immunization_pre_validator.py
- backend/tests/utils/pre_validation_test_utils.py
- backend/tests/utils/values_for_tests.py
- e2e/test_authorization.py
- e2e/test_create_immunization.py
- e2e/test_delete_immunization.py
- e2e/test_delta_immunization.py
- e2e/test_get_immunization.py
- e2e/test_s_flag_immunization.py
- e2e/test_search_immunization.py
- e2e/test_update_immunization.py
- e2e/utils/base_test.py
- e2e/utils/resource.py
- specification/components/examples/Immunization/completed_covid19_immunization_event.json
- specification/components/examples/Immunization/completed_covid19_immunization_event_filtered_for_read.json
- specification/components/examples/Immunization/completed_covid19_immunization_event_filtered_for_read_and_s_flag.json
- specification/components/examples/Immunization/completed_covid19_immunization_event_filtered_for_search.json
- specification/components/examples/Immunization/completed_covid19_immunization_event_filtered_for_search_and_s_flag.json
- specification/components/examples/Immunization/completed_covid19_immunization_event_mandatory_fields_only.json
- specification/components/examples/Immunization/completed_flu_immunization_event.json
- specification/components/examples/Immunization/completed_hpv_immunization_event.json
- specification/components/examples/Immunization/completed_mmr_immunization_event.json
> Amb 2165 validation amendments allow dates for date times

- backend/src/models/fhir_immunization_pre_validators.py
- backend/tests/test_immunization_pre_validator.py
> Amb 2172 validation amendments resource ids

- backend/src/mappings.py
- backend/src/models/validation_sets.py
- backend/tests/sample_data/completed_rsv_immunization_event.json
- backend/tests/test_immunization_post_validator.py
- backend/tests/test_utils.py
- e2e/lib/authentication.py
- e2e/test_create_immunization.py
- e2e/test_delete_immunization.py
- e2e/test_get_immunization.py
- e2e/test_search_immunization.py
- e2e/test_update_immunization.py
- e2e/utils/factories.py
- e2e/utils/mappings.py
- specification/components/examples/Immunization/completed_rsv_immunization_event.json
- specification/components/examples/Immunization/completed_rsv_immunization_event_filtered_for_read.json
> AMB-2255 : RSV-Uplift

- specification/immunisation-fhir-api.yaml
> Changes to be in sync with release document

- sandbox/immunisation-fhir-api.json
- specification/immunisation-fhir-api.json
> changes related to sandbox

- sonar-project.properties
> Added sonarcloud config

- backend/src/models/fhir_immunization_pre_validators.py
- backend/src/models/utils/pre_validator_utils.py
- backend/tests/sample_data/completed_hpv_immunization_event.json
- backend/tests/sample_data/sample_immunization_field_mappings.json
- backend/tests/test_immunization_pre_validator.py
- backend/tests/utils/pre_validation_test_utils.py
> AMB-2194-Pre-validation 2 updates

- specification/immunisation-fhir-api.yaml
> Update schema and response for RSV

- azure/azure-pr-teardown-pipeline.yml
- terraform/api_gateway/mtls_cert.tf
- terraform/splunk/backup.tf
> AMB-0009-New-Imms-Account-changes

- sandbox/immunisation-fhir-api.json
- specification/immunisation-fhir-api.json
- specification/immunisation-fhir-api.yaml
> Updated response for sandbox

- backend/src/fhir_repository.py
- backend/src/fhir_service.py
- e2e/test_create_immunization.py
> Raise duplicate error even when initial event is deleted

- sandbox/immunisation-fhir-api.json
> updated field descriptions along with schema

- terraform/configs.tf
- terraform/delta.tf
- terraform/delta_db.tf
- terraform/imms_db.tf
- terraform/lambda.tf
> AMB-2292-pentester-fixes-for-imms-fhir-api

- .github/workflows/sonarcloud.yml
> AMB 2232 - Sonarcloud

- azure/azure-release-pipeline.yml
> AMB-0008-Production-deployment-preparations

- azure/templates/post-deploy.yml
> AMB-0008-Fixing-prod-test-for-terraform

- azure/azure-release-pipeline.yml
> AMB-0008-Production-aws-endpoint-correction

- azure/templates/post-deploy.yml
- e2e/lib/env.py
> AMB-0009-Correct-the-run-full-test-suite

- backend/src/models/fhir_immunization.py
- backend/src/models/fhir_immunization_pre_validators.py
- backend/src/models/field_locations.py
- backend/src/models/obtain_field_value.py
- backend/tests/test_immunization_post_validator.py
- backend/tests/test_immunization_pre_validator.py
- sandbox/immunisation-fhir-api.json
> Validation changes for postalCode

- azure/azure-build-pipeline.yml
- azure/templates/build.yml
- delta_backend/src/delta.py
> AMB-0008-Sandbox-build

- sandbox/immunisation-fhir-api.json
> updated create schema

- ack_backend/src/ack_processor.py
- ack_backend/src/update_ack_file.py
- backend/src/fhir_batch_repository.py
- backend/src/forwarding_batch_lambda.py
- backend/src/models/errors.py
- recordprocessor/src/batch_processing.py
- terraform/api_gateway/mtls_cert.tf
- terraform/forwarder_lambda.tf
> AMB-0009-ACk-file-writing

- azure/azure-prod-release-pipeline.yml
- infra/audit_db.tf
- infra/delta_db.tf
- infra/imms_db.tf
- terraform/delta.tf
- terraform/dps_role_creation.tf
- terraform/endpoints.tf
- terraform/file_name_processor.tf
- terraform/forwarder_lambda.tf
- terraform/outputs.tf
- terraform/variables.tf
- terraform_aws_backup/aws-backup-destination/main.tf
> AMB-2235-Blue-Green-Deployments-Part-A

- azure/azure-release-pipeline.yml
> AMB-2235-Blue-Green-Deployments-B

- infra/audit_db.tf
> AMB-2235-Blue-Green-Test

- infra/audit_db.tf
> AMB-2235-Fix-release-pipeline

- azure/azure-prod-release-pipeline.yml
- azure/azure-release-pipeline.yml
> AMB-2235-Fix-release

- ack_backend/Dockerfile
- backend/batch.Dockerfile
- backend/lambda.Dockerfile
- delta_backend/Dockerfile
- filenameprocessor/Dockerfile
- recordprocessor/Dockerfile
- sandbox/Dockerfile
- temporary_sandbox/Dockerfile
> AMB-2335-Tech Debt - Dockerfile Root User in Use

- azure/azure-pr-pipeline.yml
- azure/azure-prod-release-pipeline.yml
- azure/azure-release-pipeline.yml
- azure/templates/deploy-manual-approval.yml
- azure/templates/deploy-stage.yml
- azure/templates/deploy-stages.yml
- azure/templates/post-prod-deploy.yml
> AMB-2235-Blue-Green-Deploy

- azure/azure-release-pipeline.yml
- terraform_aws_backup/aws-backup-destination/modules/aws_config/kms_key.tf
- terraform_aws_backup/aws-backup-source/main.tf
- terraform_aws_backup/aws-backup-source/modules/aws_config/s3_report_config.tf
> AMB-9999-Url-fix

- ack_backend/src/ack_processor.py
- ack_backend/src/audit_table.py
- ack_backend/src/update_ack_file.py
- ack_backend/src/utils_for_ack_lambda.py
- delta_backend/src/delta.py
- filenameprocessor/src/audit_table.py
- filenameprocessor/src/file_name_processor.py
- filenameprocessor/src/utils_for_filenameprocessor.py
- infra/non-prod/audit_db.tf
- infra/prod/endpoints.tf
- infra/prod/s3_dest_bucket.tf
- infra/prod/s3_source_bucket.tf
- recordprocessor/src/audit_table.py
- recordprocessor/src/file_level_validation.py
- recordprocessor/src/utils_for_recordprocessor.py
- terraform_aws_backup/aws-backup-destination/main.tf
- terraform_aws_backup/aws-backup-destination/modules/aws_config/variables.tf
- terraform_aws_backup/aws-backup-source/main.tf
- terraform_aws_backup/aws-backup-source/modules/aws_config/s3_report_config.tf
> AMB-9999-Forward_fix

- filenameprocessor/src/audit_table.py
- filenameprocessor/src/file_name_processor.py
- filenameprocessor/tests/test_audit_table.py
- filenameprocessor/tests/test_elasticache.py
- filenameprocessor/tests/test_file_key_validation.py
- filenameprocessor/tests/test_lambda_handler.py
- filenameprocessor/tests/test_logging_decorator.py
- filenameprocessor/tests/test_make_and_upload_ack_file.py
- filenameprocessor/tests/test_send_sqs_message.py
- filenameprocessor/tests/test_utils_for_filenameprocessor.py
- filenameprocessor/tests/utils_for_tests/generic_setup_and_teardown.py
- filenameprocessor/tests/utils_for_tests/utils_for_filenameprocessor_tests.py
- filenameprocessor/tests/utils_for_tests/values_for_tests.py
> Amb 2382 test audit table file movement file name processor

- backend/src/filter.py
- backend/tests/sample_data/completed_covid19_immunization_event_filtered_for_search_using_bundle_patient_resource.json
- specification/components/examples/Immunization/completed_covid19_immunization_event_filtered_for_search.json
> Remove location overwrite for search

- e2e_batch/constants.py
> AMB-2347 : Immunisation Batch End to End Automation  Testing REF few changes

- recordprocessor/tests/test_audit_table.py
- recordprocessor/tests/test_utils_for_recordprocessor.py
- recordprocessor/tests/utils_for_recordprocessor_tests/generic_setup_and_teardown.py
- recordprocessor/tests/utils_for_recordprocessor_tests/mock_environment_variables.py
- recordprocessor/tests/utils_for_recordprocessor_tests/utils_for_recordprocessor_tests.py
- recordprocessor/tests/utils_for_recordprocessor_tests/values_for_recordprocessor_tests.py
> AMB-2384-Test- record-processor-audit-file-movement

- azure/templates/post-deploy.yml
- e2e/test_proxy.py
- e2e/utils/immunisation_api.py
Proxy e2e test switched to use exponential back-off
> VED-234 E2E tests fix proxy

- filenameprocessor/Makefile
- filenameprocessor/src/file_name_processor.py
- filenameprocessor/src/logging_decorator.py
- filenameprocessor/tests/test_lambda_handler.py
- filenameprocessor/tests/test_logging_decorator.py
Improved error message sent to Splunk to include vaccineType and supplier
> VED-58 Batch improved error logging

- delta_backend/src/Converter.py
- Fix breaking changes by adding Timezone awareness
> VED-265-FHIR-TO-FLAT-JSON

- terraform/ack_lambda.tf
- terraform/delta.tf
- terraform/ecs_batch_processor_config.tf
- terraform/file_name_processor.tf
- terraform/forwarder_lambda.tf
- terraform/lambda.tf
- terraform/lambda/lambda.tf
- terraform/mesh_processor.tf
> VED-299: Pin module versions to fix docker build.

- sandbox/immunisation-fhir-api.json
- specification/immunisation-fhir-api.json
> VED-109-OAS2

- ack_backend/poetry.lock
- ack_backend/pyproject.toml
- backend/poetry.lock
- backend/pyproject.toml
- delta_backend/poetry.lock
- delta_backend/pyproject.toml
- filenameprocessor/poetry.lock
- filenameprocessor/pyproject.toml
- mesh_processor/poetry.lock
- mesh_processor/pyproject.toml
- recordprocessor/poetry.lock
- recordprocessor/pyproject.toml
> VED-153: Dependency updates round 3.

- delta_backend/src/delta.py
- delta_backend/src/extractor.py
Fix records being omitted from the delta due to the boto3 DynamoDB serialiser not handling floats.
> TypeError: Float types are not supported. Use Decimal types instead.
> Fix float serialisation issue.

- delta_backend/tests/test_convert_dose_amount.py
- delta_backend/tests/test_delta.py
Unit test to cover float/decimal error writing JSON to Delta DynamoDB
> VED-322 Float Serialisation Unit Test

- .github/dependabot.yml
> VED-153: Group minor and patch updates from Dependabot.

- infra/endpoints.tf
> VED-335: Revert VPCE policy changes to fix batch issue.

- azure/templates/post-deploy.yml
> VED-353: Wait for API to be available before running e2e tests.

- redis_sync/src/redis_cacher.py
- redis_sync/tests/test_redis_cacher.py
> VED-381: Fix deletion of old keys.

- redis_sync/src/transform_map.py
> VED-26: Fix import.

- terraform/s3_config.tf
- terraform/variables.tf
> VED-446-new-s3-name fhir-config

- terraform/mesh_processor.tf
> VED-355: Fix permissions for creating MESH S3 bucket event notification.

- .github/workflows/pr-lint.yaml
* Routine Changee
**Changes:**
- Removed duplicated references to the amb JIRA project.
- Added checks for the ved JIRA project, which seems to be the one that this team is using. **Please could someone** advise if any of the others can be removed and if there is anything we additionally need.
- Modified the pr-lint workflow to only run when the PR is opened (i.e. once). Previously it was being run on every synchronize event, which seems unecessary.
- Note: I have left the pr-lint workflow mostly unchanged, such that if it fails for any reason it will continue-on-error and not block. This hopefully will minimise noise (not sure how strict we are about branch name rules), but the benefit of …
> VED-XXX Fix up PR link github action

- terraform/dps_role_creation.tf
- terraform/id_sync_lambda.tf
- terraform/sqs_id_sync.tf
> VED-726: Add missing BatchGetItem permission for DPS.

- azure/azure-pr-teardown-pipeline.yml
> VED-711: Fix PR teardown pipeline.

- terraform/dynamodb.tf
> VED-711: Disable deletion protection on PR branch deploys.

- filenameprocessor/src/constants.py
Include support just in case for CRLF with a newline.
> VED-757 Update constant for empty file threshold

- delta_backend/src/extractor.py
> VED-759: Don't fail delta conversion for missing date fields.

- filenameprocessor/src/file_validation.py
- filenameprocessor/tests/test_file_key_validation.py
Suggestion to include ODS code optionally at the end of the filename to ensure uniqueness for certain supplier systems.
> VED-763 Permit ODS code in the filename

- config/prod/permissions_config.json
> Add FLU Read and Search permissions for MAVIS.
